server:
  port: 5000
zuul:
  routes:
    BubblesService:                        ## 认证服务
      path: /demo/**                    ## 匹配路径
      service-id: LoadBalanceDemo

spring:
  application:
    name: APIPorxy
